### ISSUE TITLE
HTTP Tracking

### ISSUE THREAD

**Issue by wbhob** [orbital-js/orbital#2]
@boat/http is based on the `request` library, and allows you to request other APIs from your own API. This issue is to track features for the HTTP module.

- [x] Base options from Angular, and Option transformation to `request` compatible options
- [x] Common `request` method on Http class
- [ ] Create mocking interface (backlog)
